const questions=[
["Eines Morgens ___ der schlaue Fuchs durch den Wald.","schleichen",["schlich","schleichte","schleich"],"schlich","‚Schleichen‘ ist ein starkes Verb. Der Stammvokal verändert sich: ei → i."],
["Am Bach ___ er einen hungrigen Raben.","entdecken",["entdeckte","entduckte","entdeckete"],"entdeckte","Bei einem regelmäßigen Verb setzt du -te an den Verbstamm."],
["Der Rabe ___ ein großes Stück Käse im Schnabel.","halten",["haltete","hielt","holte"],"hielt","‚Halten‘ ist unregelmäßig. Im Präteritum heißt es ‚hielt‘."],
["Der Fuchs ___ den köstlichen Käse sofort.","bemerken",["bemerkte","bemark","bemerkete"],"bemerkte","Verbstamm ‚bemerk-‘ + Endung ‚-te‘ ergibt ‚bemerkte‘."],
["Daraufhin ___ er den Raben überschwänglich.","loben",["lobte","lieb","lobete"],"lobte","‚Loben‘ ist regelmäßig: lob- + -te."],
["Der geschmeichelte Rabe ___ seinen Schnabel.","öffnen",["offnete","öffnete","öffnete-te"],"öffnete","Nach dem Verbstamm ‚öffn-‘ hilft ein zusätzliches e bei der Aussprache."],
["Der Käse ___ direkt vor die Pfoten des Fuchses.","fallen",["fällte","fiel","fallte"],"fiel","‚Fallen‘ ist stark. Der Stammvokal verändert sich: a → ie."],
["Der Fuchs ___ die Beute und verschwand zufrieden.","nehmen",["nahm","nehmte","nahmte"],"nahm","‚Nehmen‘ ist stark. Im Präteritum heißt es ‚nahm‘."]];
const subjects={deutsch:["Deutsch","Grammatik, Literatur und Schreiben","▤","terracotta"],spanisch:["Spanisch","Lengua, cultura y comunicación","Ñ","petrol"],medien:["Medienunterricht","Sicher und kompetent in der digitalen Welt","⌘","petrol-light"],sonstiges:["Sonstiges","Weitere Materialien für den Unterricht","✦","brown"]};
let view="home",index=0,score=0,choice="",checked=false,started=false;
const app=document.querySelector("#app");
document.querySelector("[data-go=home]").addEventListener("click",()=>go("home"));
function go(next){view=next;if(next==="praeteritum"){started=false;reset()}render();scrollTo({top:0,behavior:"smooth"})}
function reset(){index=0;score=0;choice="";checked=false}
function crumbs(items){return `<nav class="breadcrumbs"><button data-go="home">⌂ Startseite</button>${items.map((x,i)=>`<b>/</b>${x[1]?`<button data-go="${x[1]}">${x[0]}</button>`:`<em>${x[0]}</em>`}`).join("")}</nav>`}
function bindNav(){document.querySelectorAll("[data-go]").forEach(el=>el.addEventListener("click",()=>go(el.dataset.go)))}
function render(){if(view==="home")renderHome();else if(subjects[view])renderSubject(view);else if(view==="klasse6")renderGrade();else renderLesson();bindNav()}
function renderHome(){app.innerHTML=`<div class="catalog-page"><section class="catalog-hero"><p class="eyebrow">✦ Digitale Lernmaterialien</p><h1>Interaktive<br><em>Lernumgebungen</em></h1><p>Wähle ein Fach und entdecke die verfügbaren Übungen und Lernmaterialien.</p></section><section class="catalog-section"><div class="section-heading"><span>01</span><h2>Fachbereiche</h2></div><div class="subject-grid">${Object.entries(subjects).map(([key,[label,intro,icon,tone]])=>`<button class="subject-card ${tone}" data-go="${key}"><span class="subject-icon">${icon}</span><span><strong>${label}</strong><small>${intro}</small></span><i>→</i></button>`).join("")}</div></section></div>`}
function renderSubject(key){const [label,intro,icon,tone]=subjects[key];app.innerHTML=`<div class="catalog-page inner-page">${crumbs([[label]])}<section class="inner-hero ${tone}"><span class="inner-icon">${icon}</span><div><p class="eyebrow">Fachbereich</p><h1>${label}</h1><p>${intro}</p></div></section><section class="catalog-section"><div class="section-heading"><span>02</span><h2>Jahrgangsstufen</h2></div>${key==="deutsch"?`<div class="grade-grid"><button class="grade-card" data-go="klasse6"><span class="grade-number">6</span><span><strong>Klasse 6</strong><small>Grammatik und Fabeln</small><i>Materialien ansehen →</i></span></button></div>`:`<div class="empty-state"><strong>▱</strong><div><h3>Hier entsteht etwas Neues</h3><p>Sobald die erste Übung für diesen Bereich fertig ist, erscheint hier die passende Jahrgangsstufe.</p></div></div>`}</section></div>`}
function renderGrade(){app.innerHTML=`<div class="catalog-page inner-page">${crumbs([["Deutsch","deutsch"],["Klasse 6"]])}<section class="inner-hero terracotta"><span class="inner-icon">6</span><div><p class="eyebrow">Deutsch · Jahrgangsstufe</p><h1>Klasse 6</h1><p>Interaktive Übungen und Lernangebote für den Deutschunterricht.</p></div></section><section class="catalog-section"><div class="section-heading"><span>03</span><h2>Lernmaterialien</h2></div><button class="material-card" data-go="praeteritum"><span class="material-art">Prä<br>ter</span><span class="material-copy"><small>Grammatik · Fabeln</small><strong>Verben im Präteritum</strong><p>Regelmäßige und unregelmäßige Verbformen in einer Fabel erkennen und einsetzen.</p><i>Übung öffnen →</i></span></button></section></div>`}
function lessonCrumbs(){return crumbs([["Deutsch","deutsch"],["Klasse 6","klasse6"],["Präteritum"]])}
function renderLesson(){if(!started)return renderLessonStart();if(index>=questions.length)return renderResult();renderQuiz()}
function renderLessonStart(){app.innerHTML=`<div class="catalog-page inner-page">${lessonCrumbs()}<div class="landing compact-landing"><section class="hero"><div class="eyebrow">✦ Selbstständig üben</div><h1>Verben im<br><em>Präteritum</em></h1><p>Begleite Fuchs und Rabe durch eine kleine Fabel. Wähle jeweils die passende Verbform und erhalte sofort eine Rückmeldung.</p><button class="primary-button" id="start">Übung starten →</button><div class="meta-row"><span>8 Aufgaben</span><span>ca. 5 Minuten</span><span>direkte Auswertung</span></div></section><aside class="lesson-card"><span class="card-number">01</span><div class="animal-seal">F &amp; R</div><div><p class="card-kicker">Grammatiktraining</p><h2>Der Fuchs und der Rabe</h2><p>Regelmäßige und unregelmäßige Verben sicher unterscheiden.</p></div></aside><details class="rule-box"><summary>▤ Merkhilfe zum Präteritum</summary><div class="rule-grid"><p><strong>Regelmäßig:</strong><br>Verbstamm + <mark>-te</mark><br>loben → lobte</p><p><strong>Unregelmäßig:</strong><br>Der Stamm verändert sich.<br>fallen → fiel</p></div></details></div></div>`;document.querySelector("#start").addEventListener("click",()=>{started=true;render()})}
function renderQuiz(){const [sentence,infinitive,answers,correct,hint]=questions[index];app.innerHTML=`<div class="catalog-page inner-page">${lessonCrumbs()}<section class="quiz-wrap"><div class="quiz-heading"><div><p>Aufgabe ${index+1} von 8</p><h1>Setze das Verb ins Präteritum.</h1></div><span class="score">${score} Punkte</span></div><div class="progress"><span style="width:${index/8*100}%"></span></div><article class="question-card"><span class="infinitive">Infinitiv: <strong>${infinitive}</strong></span><p class="sentence">${sentence}</p><div class="answer-list">${answers.map(a=>`<button class="answer" data-answer="${a}">${a}</button>`).join("")}</div><div id="feedback"></div><div class="quiz-actions"><button class="primary-button" id="action" disabled>Antwort prüfen</button></div></article></section></div>`;bindNav();document.querySelectorAll(".answer").forEach(b=>b.addEventListener("click",()=>{if(checked)return;choice=b.dataset.answer;document.querySelectorAll(".answer").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");document.querySelector("#action").disabled=false}));document.querySelector("#action").addEventListener("click",()=>{if(!checked){checked=true;const good=choice===correct;if(good)score++;document.querySelectorAll(".answer").forEach(b=>{b.disabled=true;if(b.dataset.answer===correct)b.classList.add("correct");else if(b.dataset.answer===choice)b.classList.add("wrong")});document.querySelector("#feedback").innerHTML=`<div class="feedback ${good?'good':'try-again'}"><strong>${good?'Richtig!':`Fast! Richtig ist „${correct}“.`}</strong><span>${hint}</span></div>`;const a=document.querySelector("#action");a.disabled=false;a.textContent=index===7?'Ergebnis ansehen':'Nächste Aufgabe →';document.querySelector(".progress span").style.width=`${(index+1)/8*100}%`}else{checked=false;choice="";index++;render()}})}
function renderResult(){const text=score===8?"Fabelhaft! Du beherrschst das Präteritum sehr sicher.":score>=6?"Sehr gut! Nur wenige Formen solltest du noch einmal ansehen.":score>=4?"Gut angefangen! Mit einer zweiten Runde wirst du noch sicherer.":"Bleib dran! Lies die Merkhilfe und probiere die Übung noch einmal.";app.innerHTML=`<div class="catalog-page inner-page">${lessonCrumbs()}<section class="result-card"><div class="result-icon">✒</div><p class="eyebrow">Übung abgeschlossen</p><h1>${score} von 8 richtig</h1><p>${text}</p><div class="score-track">${questions.map((_,i)=>`<span class="${i<score?'filled':''}"></span>`).join("")}</div><button class="primary-button" id="restart">↻ Noch einmal üben</button></section></div>`;bindNav();document.querySelector("#restart").addEventListener("click",()=>{reset();started=true;render()})}
render();
